feat: Init project with TS and Storybook
dcTeam7/CalenDog pull request #15
Opened 2023-04-06 18:26 UTC by rafaelspanholi

#2  Create base project with Storybook Vite and Typescript

2023-04-06 18:33 UTC, KevinDik approved these changes

2023-04-07 00:16 UTC, mikaelmonteirodev approved these changes

2023-04-07 17:19 UTC, AbraaoAlves requested changes

2023-04-07 17:19 UTC, AbraaoAlves commented on calenDog/index.html
> +    <title>Vite + React + TS</title>
Please, change title content to Calendog

``` suggestion
<title>Calendog</title>
```

2023-04-07 17:20 UTC, merged