feat: Create requirements in README.md
dcTeam7/CalenDog pull request #20
Opened 2023-04-08 14:14 UTC by KevinDik

CalenDog #3 Criado requisitos do README.md e Criado campos para separação das tasks

2023-04-09 18:28 UTC, alanafilgueiras approved these changes

2023-04-11 12:14 UTC, AbraaoAlves requested changes

2023-04-11 18:27 UTC, KevinDik commented on README.md
> +
@AbraaoAlves Correções realizadas.

2023-04-12 12:52 UTC, alanafilgueiras approved these changes

2023-04-13 13:17 UTC, AbraaoAlves approved these changes

2023-04-13 18:33 UTC, merged