8 calendog contribuidores documentação do readme
dcTeam7/CalenDog pull request #24
Opened 2023-04-13 18:45 UTC by fabrjcio

closes #8

2023-04-14 12:16 UTC, alanafilgueiras approved these changes

2023-04-14 15:29 UTC, KevinDik approved these changes

2023-04-14 15:29 UTC, KevinDik commented on README.md
Nice code

2023-04-14 17:39 UTC, KevinDik requested changes

2023-04-14 17:39 UTC, KevinDik commented on README.md
@mikaelmonteirodev Atualiza tua branch com as informações que foram mergiadas recentemente.

2023-04-15 01:05 UTC, fabrjcio commented on README.md
Atualizada!

2023-04-15 19:37 UTC, KevinDik commented on README.md
ok

2023-04-15 19:37 UTC, merged